[package]
name = "rubon"
version = "0.1.0"
edition = "2021"
license = "MIT"


[dependencies]
ziku-algorithms = "0.1.3"
libp2p-core = { version = "0.36.0", default-features = false }
prost = "0.11"


[build-dependencies]
prost-build = "0.11"
